# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='person',
            name='curse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.curse'),
            preserve_default=False,
        ),
    ]
