# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180608_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='curse',
        ),
        migrations.AddField(
            model_name='person',
            name='curse',
            field=models.ManyToManyField(to='person.curse'),
        ),
    ]
